### ISSUE TITLE
Release v0.2

### ISSUE THREAD

**Issue by flosse** [ethercat-rs/ethercat#12]
- [x] Implement `get_sdo` & `get_sdo_entry` (#11)
- [x] Implement `get_pdo` & `get_pdo_entry` (#13)
- [x] Use new-type pattern for indexes (#14)
- [x] Implement `get_sync` (bee0d75e22c5e2c63294003341e8f4deac0d0cfe)
- [x] Add some basic debug logs (c3bd08288fc6379191bb9657873da5ae0ff17620)
- [x] Improve errors (20c21269c1acb80b6c01bbe3c78a24daa8cc9645)
- [x] ethercat-sys: generate ioctl numbers from master header (#18)
- [x] Make it compile with upstream IgH Master (#20, #22)
- [x] Install basic CI (#21, #19)
- [x] include pregenerated bindings (#23, #29)
- [x] release `ethercat-types` crate `v0.3.0` and remove `patch` in `ethercat/Cargo.toml`
- [x] Add `CHANGELOG.md`
- [x] release `ethercat-sys` crate `v0.2.0` (#28)
- [x] Make sure all examples work with some real hardware (#3)
- [x] Publish on crates.io

**Comment by birkenfeld** [comment]
:+1: - I had no time to review the PRs due to holidays, but it all looks good.

**Comment by flosse** [comment]
done :)
